### ISSUE TITLE
compilation broken on 2.0.0-beta.5 due to missing manifest dependency

### ISSUE THREAD

**Issue by tayloraswift** [hummingbird-project/hummingbird-lambda#31]
we are [failing to build docs for 2.0.0-beta.5](https://static.swiftinit.org/builds/67528/ssgc.log) on Swiftinit due to the following error:

```
/home/ubuntu/unidoc/checkouts/hummingbird-lambda/.build.ssgc/checkouts/hummingbird/Sources/HummingbirdCore/Request/RequestBody.swift:15:8: error: no such module 'Collections'
import Collections
       ^
```

compiling locally with `--explicit-target-dependency-import-check=error` reveals the problem:

```
error: Target HummingbirdCore imports another target (Collections) in the package without declaring it a dependency.
```

**Comment by adam-fowler** [comment]
I never saw this issue on my macOS, Linux CI was not complaining then as soon as you post this issue the examples CI failed. I cannot replicate this locally but anyway it obviously an issue so added dependency and did a new release of Hummingbird
